<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>  <!-- Add this line -->
        <LangVersion>default</LangVersion>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <PlatformTarget>x86</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="s3pi.Interfaces">
          <HintPath>..\..\..\Desktop\sims3-package-interface-main\S3PI-Library-DLLs\s3pi.Interfaces.dll</HintPath>
        </Reference>
        <Reference Include="s3pi.Package">
          <HintPath>..\..\..\Desktop\sims3-package-interface-main\S3PI-Library-DLLs\s3pi.Package.dll</HintPath>
        </Reference>
        <Reference Include="s3pi.ScriptResource">
          <HintPath>..\..\..\Desktop\sims3-package-interface-main\S3PI-Library-DLLs\s3pi.ScriptResource.dll</HintPath>
        </Reference>
        <Reference Include="s3pi.Settings">
          <HintPath>..\..\..\Desktop\sims3-package-interface-main\S3PI-Library-DLLs\s3pi.Settings.dll</HintPath>
        </Reference>
        <Reference Include="s3pi.WrapperDealer">
          <HintPath>..\..\..\Desktop\sims3-package-interface-main\S3PI-Library-DLLs\s3pi.WrapperDealer.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Costura.Fody" Version="6.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>